export default {
   POPULAR_LOAD_SUCCESS: 'POPULAR_LOAD_SUCCESS',
   POPULAR_LOAD_FAIL: 'POPULAR_LOAD_FAIL',
   POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
   POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL', 
}